### ISSUE TITLE
Remove original wordpress files

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#1]
We only need to keep the theme itself, not the original wordpress files - if we move it with git mv, all file history will be retained, which is nicer than just moving it where git now thinks they're different files. 

An example command might be (from the command line in the root of the git repo)

```bash
git mv obf-new/wp-content/themes/obf-new/* .
```

This translates roughly as "please move all files from the obf-new theme directory to the root of this folder" - once that's done, you'd need to delete all the other old folders.

**Comment by yochannah** [comment]
A couple of extra notes - only do this if all the files you've edited are in the theme directory! If not, we'll need to migrate them to the theme first.

Also, we probably don't want to keep wp-config.php in the public directory - it contains the details for your mysql user/password.

**Comment by kushinauwu** [comment]
Oh! I'll move them with the command line. The config file as well, it shouldn't be out here!
