### ISSUE TITLE
Previous meeting minutes - how should the page look? 

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#11]
We've been wondering if we should make separate pages for each meeting's minutes, or a single page listing them all. Options from @kushinauwu:

1. Make one post for all the previous meetings and have all the content there. The headings can be styled differently if we use the heading tags for meeting headings and content headings accordingly. That might be harder to maybe add more content to? You'd have to write the new meeting's minutes at the top every year.
2. If we decide to make separate posts for each meeting I could make a page that loops through all the meetings posts. Might it be easier to find data from previous meetings like this?
3. Have separate posts and list them all like it currently is, except with collapsible post content that would show below the respective meeting title when clicked.

**Comment by yochannah** [comment]
@cjfields as Secretary, what are your feelings?

**Comment by yochannah** [comment]
I think I prefer 2, but not strongly so.

**Comment by cjfields** [comment]
@yochannah I think option 2, which would be easier to deal with if we decide to rework formatting at some point.

**Comment by yochannah** [comment]
Thanks @cjfields ! :)
