### ISSUE TITLE
Mobile menu hover effect

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#13]
Nice to see the menu working in mobile now! 😁  there are some strange styles going on - the blue and the purple overlap a little. I think the font size changes as we hover, too - it might be better to keep the font size consistent so things don't jump about. 
<img width="733" alt="image" src="https://user-images.githubusercontent.com/9271438/50662328-dc312080-0f9d-11e9-8867-417c0f64d0bf.png">

**Comment by kushinauwu** [comment]
![image](https://user-images.githubusercontent.com/14867092/50692583-6fc82700-105a-11e9-9543-d6b3f0d618df.png)

does this seem better?

**Comment by yochannah** [comment]
yes, mostly! I don' think we need the gap between events and BOSC, though.

**Comment by kushinauwu** [comment]
alright, fixed that! I will prepare to import on to the live site. Fingers crossed!
