### ISSUE TITLE
Show all or none of the board on the homepage?

### ISSUE THREAD

**Issue by peterjc** [kushinauwu/OBF-Homepage-New#14]
Viewing https://www-dev1.open-bio.org/ currently shows three board members (President, Treasurer, Secretary) which while key roles, the board felt it would be nicer to show all or none on the front page.

**Comment by kushinauwu** [comment]
That does sound better, I'll fix that so it shows all the members :)

**Comment by peterjc** [comment]
Great. We'll have to help with getting photos too...

**Comment by peterjc** [comment]
This seems to have been done  pending photos.

**Comment by kushinauwu** [comment]
Is that fine? The pictures can be updated at any time easily via the wordpress dashboard :) In recent discussions with @yochannah and @nlharris, the board section on the homepage might be replaced by a brief about the board #23

**Comment by yochannah** [comment]
this has been sorted.
