### ISSUE TITLE
Which projects to list on new main page?

### ISSUE THREAD

**Issue by peterjc** [kushinauwu/OBF-Homepage-New#15]
Currently https://www-dev1.open-bio.org/ has six projects and a link for more (in preparation).

https://www.open-bio.org/wiki/Projects does currently list 8 projects, of which I would view the top 5 as BioJava, BioPerl, Biopython, BioRuby, BioSQL with EMBOSS likely at 6th but the status is effectively dormant.

This ranking/selection is likely to fall to the board to decide.

**Comment by kushinauwu** [comment]
That's fair enough. I'll rearrange accordingly for now and when the board decides, the selection can be changed easily if required  :)

**Comment by peterjc** [comment]
Is the choice of six essentially dictated by the visual layout?

**Comment by kushinauwu** [comment]
Not at all! I picked 6 arbitrarily. Also, there's no problem in showing all 8 main projects on the front page either, that might actually be good too so there won't be a need to choose as such.

**Comment by yochannah** [comment]
we're now showing all.
