### ISSUE TITLE
News section - styling comments

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#16]
I love seeing the new news section!! <3 The pictures in the background of the post excerpts is a nice touch. 

A few comments: 
1. Increase contrast - it's a little hard to read the text, especially on busy background like this 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/9271438/51062513-0d899c00-15ef-11e9-80e1-144eeeb49da9.png"> (I feel so old making "It's a little hard to read" comments but oh well 😆 )
2. Sometimes the excerpt runs off the page a little: 
<img width="662" alt="image" src="https://user-images.githubusercontent.com/9271438/51063035-11b6b900-15f1-11e9-969f-42c59290ff00.png"> - this also happens to the top one at particularly narrow screen widths - I wonder if CSS grid might help with this? 
3. Some of the background images are a bit skewed - is it possible to preserve aspect ratio?

Other than that, it looks good! I tested squishing and expanding the browser window and it seems clear you've put thought into making the media queries work nicely! 👍

**Comment by kushinauwu** [comment]
![image](https://user-images.githubusercontent.com/14867092/51084816-46905080-1756-11e9-9bf5-ccce0649e76e.png)
The aspect ratio is the same as the original picture now! :)
 I increased the brightness too, haha don't worry, I found it hard to read myself when I looked it over!

**Comment by yochannah** [comment]
we're re-styling htis in another issue
