### ISSUE TITLE
Cannot view dropdown menu items on mobile

### ISSUE THREAD

**Issue by kushinauwu** [kushinauwu/OBF-Homepage-New#19]
Dropdown sub items aren't displayed as the hover effect wont apply on mobile. Clicking makes the browser load the respective top level menu item page, instead of showing the dropdown menu.

**Comment by kushinauwu** [comment]
Removed the navbar toggler and used the bootstrap toggle to fix the menu icon jumping up/down on tap.

**Comment by kushinauwu** [comment]
@yochannah  The events dropdown works fine, because the main events page is added as the calendar in the dropdown. I've used dropdowns for the projects and fellowships tab too, but they redirect to parts of the respective pages. On mobile the hover doesn't work as it tapping is considered as clicking, so the browser redirects to the page instead of showing the dropdown for long enough for anyone to tap a dropdown item. I'm wondering if it should have a menu item like "see all projects" or "see all details" in the dropdown and make the first level heading inactive like the events heading?

**Comment by yochannah** [comment]
>  I'm wondering if it should have a menu item like "see all projects" or "see all details" in the dropdown and make the first level heading inactive like the events heading?

I think that's a good solution! I did something similar when I did the InterMine site for the exact same reason :D

**Comment by kushinauwu** [comment]
Fixed this!
