### ISSUE TITLE
Add more detailed setup instructions

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#2]
This is a really great start, and I like that you've added mention of the advanced custom fields plugin. Can we make the setup instructions a little more tutorial-style, though? Something like this:

## To install the theme 
1. Install the theme via FTP to the wp-content/themes directory or upload it via the [theme upload web interface](https://codex.wordpress.org/Using_Themes#Adding_New_Themes_using_the_Administration_Panels). 

## Enable plugins and import content 
Before importing content, we'll need to activate the plugins used for some of our pages. 
1. In the Wordpress admin console, go to the plugin section and search for "Advanced custom fields". Install and activate this plugin _before_ you import the content
2. In the Wordpress admin console, go to tools > import and install the wordpress importer if it isn't already active
3. ..... etc. 

- activating the menu... (instructions here).

**Comment by kushinauwu** [comment]
You're absolutely right. I had some trouble setting it up myself when importing the theme. Will fix that up!

**Comment by yochannah** [comment]
The new setup instructions are amazing!! ❤️ just the right level of detail
