### ISSUE TITLE
Replace current photos with BOSC-ey photos

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#20]
I've gone through Berenice's photos and favourited some of the more generic ones that don't have lots of faces in them: https://www.flickr.com/photos/137690418@N06/favorites/ can we use these to replace the current photos? 

These in particular might be good for prominent areas:

- https://www.flickr.com/photos/134305289@N03/35287390194/in/faves-137690418@N06/
- https://www.flickr.com/photos/134305289@N03/42394043775/in/faves-137690418@N06/
- https://www.flickr.com/photos/134305289@N03/43248795832/in/faves-137690418@N06/ (not sure this one will work, Nomi might be too far away from the slides?) 

If you still think these don't fit or you don't have enough, let me know!

**Comment by kushinauwu** [comment]
I think these photos will work great! I'll add them in and show you how it looks :)

**Comment by yochannah** [comment]
A few more photo sources suggested by @nlharris, where we already have permissions from the photographees to use the photos:

1. The recent BOSC reports: https://www.ncbi.nlm.nih.gov/pmc/?term=BOSC+OBF 
2. Any pics from https://news.open-bio.org/

**Comment by yochannah** [comment]
I love seeing the new photos on the homepage by the way! Could we perhaps swap the poster photo to be the top photo? 👍

**Comment by yochannah** [comment]
Adding a small to-do here - I love the ladybird photo on the homepage but it might be nice to replace it with a more topical photo ;)

**Comment by yochannah** [comment]
+ @nlharris has asked if we coudl add pics to the BOSC pages

**Comment by nlharris** [comment]
can we replace the photos on the OBF home page? in the first photo, the people looking at posters seem to be all guys. the second photo is badly lit and kind of dull. the third is a pretty but irrelevant beetle.
were there some photos from GCCBOSC 2018 that could be used?

**Comment by yochannah** [comment]
@nlharris maybe you could select which photos you like? I selected some of the photos that I liked here: https://www.flickr.com/photos/137690418@N06/favorites/ but there might be others from GCCBOSC that you like better.

**Comment by nlharris** [comment]
The first 7 you have in your flickr look good (though the narrow one of the people at the poster session from above seems distorted). I'll also send you some other suggestions.

**Comment by nlharris** [comment]
Hmm, the aspect ratio of the first photo on the home page is looking weird again to me (maybe I hadn't shift-reloaded the page before when I said it looked ok?).

**Comment by kushinauwu** [comment]
That was a mistake on my end, sorry! I'd set a fixed height,so that happened. Scaled the images down so the whitespace problem should be a little better now!
also, I added pictures to the 'Get involved' part in the BOSC pages. Should I add more on the BOSC homepage as well?

**Comment by nlharris** [comment]
> Should I add more on the BOSC homepage as well?

yes please! most of the photos i suggested are from BOSC.

it would be appropriate to add a photo of the org committee near where the org committee is listed, and i'd like there to be a photo from the conference (maybe one of the poster session photos) near the top.

**Comment by nlharris** [comment]
the image that's currently at the top of the bosc page (the ISMB one with the red plus sign) could move down--maybe to the top or bottom of the Important Dates box? also, that image should link to the ISMB site: https://www.iscb.org/ismbeccb2019

**Comment by nlharris** [comment]
i like the photos you added to the "get involved section", except for the "review abstracts" one, which looks like name badges? maybe could use a picture from the poster session there, since many people's posters are more or less abstracts. :-)

**Comment by nlharris** [comment]
looks good!
