### ISSUE TITLE
Reusable blocks an option for BOSC content?

### ISSUE THREAD

**Issue by kushinauwu** [kushinauwu/OBF-Homepage-New#21]
This might be helpful for retaining the BOSC page structure as well as changing the order of content maybe?
There's this thing in the new editor called 'Reusable Blocks', and it lets you turn a block into a reusable one, including its custom styles.

![reusable block](https://user-images.githubusercontent.com/14867092/52535369-9c671100-2d73-11e9-8cda-3be33cdaea70.JPG)

So I tried using one and named it and made a test page with the bosc template as the page attributes.
![resuable blocks 2](https://user-images.githubusercontent.com/14867092/52535371-a25cf200-2d73-11e9-8fd6-ea06045c95fb.JPG)

And once i selected this option it imported all that content but I could still edit it
![resuable blocks 3](https://user-images.githubusercontent.com/14867092/52535374-a557e280-2d73-11e9-9397-0b384d293ad9.JPG)

And it looks just like the default page! 
![resuable blocks 4](https://user-images.githubusercontent.com/14867092/52535376-a852d300-2d73-11e9-9f7e-513b4dc37372.JPG)

Could this be useful? And easy to use?

**Comment by yochannah** [comment]
That looks handy! I'd like to hear @nlharris's thoughts.

@nlharris for context - we've been wondering what to do when BOSC 2020 comes around. Presumably we want to preserve the 2019 content and migrate it to an archive somewhere, and then replace those pages with the 2020 content. @kushinauwu's approach above would allow us to manually create new pages that look the same as the older pages.

One thing I wonder is if there is some way to wholesale migrate all of the 2019 pages to the archive and create a fresh new batch of 2020 pages, but that might not be necessary or even possible in the weeks we have left.

**Comment by kushinauwu** [comment]
Fixed this issue by using a function to duplicate page from https://www.hostinger.in/tutorials/how-to-duplicate-wordpress-page-post, which also adds a 'Duplicate' button, leaving the base page unchanged.
