### ISSUE TITLE
Show event dates in text format instead of dd/mm/yyyy

### ISSUE THREAD

**Issue by kushinauwu** [kushinauwu/OBF-Homepage-New#22]
Change dates to text so it is consistent for UK and US date styles.

**Comment by peterjc** [comment]
Personally I have a fondness for the ISO 8601 standard yyyy-mm-dd which is clear to everyone (although most familiar to residents of Japan perhaps)?

https://www.iso.org/iso-8601-date-and-time-format.html

Given our largely technical audience, this might be a good compromise?

**Comment by yochannah** [comment]
I think this is a nicely unambiguous way, but I can also see why text dates, e.g. "September 12, 2019" might look presentationally nicer. Either works in my opinion but I'm curious what @nlharris might think?

**Comment by nlharris** [comment]
I agree with Peter (though I realize that I did initially say I wanted text). yyyy-mm-dd is unambiguous and also sortable.

**Comment by kushinauwu** [comment]
Used the yyyy-mm-dd standard for the events :)
