### ISSUE TITLE
Timeline issues on about page

### ISSUE THREAD

**Issue by kushinauwu** [kushinauwu/OBF-Homepage-New#24]
- [x] Excess whitespace above/below timeline

- [x] Move original projects' positions to 2001

- [x]  Remove hover class so the all the years' contents are visible and left align text

- [x] Add "First BOSC" for 2000 with a pear icon

- [x] Replace "Giving up of..." text with “OBF becomes an associate project of Software in the Public Interest, Inc., a fiscal sponsorship organization.”

- [x] Timeline is making the menu shift out of screen bounds on mobile. consider making the timeline vertical altogether.

**Comment by kushinauwu** [comment]
I made the timeline vertical instead because the horizontal one was messing with the width of the body, and removed the hover too.

**Comment by yochannah** [comment]
**looks:** It looks really great now, and I LOVE THE WAY IT SWITCHES WHEN I RESIZE THE BROWSER!!! 😻 

**editing:** I tried duplicating the blocks to add a timeline event and I think I added many. Oops!

**Comment by kushinauwu** [comment]
Oh sorry! I separated the blocks now! XD So only one will get added with block duplication

**Comment by kushinauwu** [comment]
So, wordpress just merged the separated blocks together. :|

**Comment by yochannah** [comment]
we'll consider only using hte code editor tp update this page.

**Comment by nlharris** [comment]
I was going to report that there are duplicates in the (very cool) timeline--looks like you're already on it!
Could the bioperl etc. logos be placed side-by-side to take up less vertical space? The BioJava one in particular seems to have excess whitespace below it.

**Comment by kushinauwu** [comment]
The Biojava one probably seems like tht because the logo is more horizontal, but it seemed a little weird to  keep it like that to me too. maybe I could add a border around the logos so it seems better?
Added a metabox for the timeline edits!
![image](https://user-images.githubusercontent.com/14867092/53524423-58ab3000-3b05-11e9-98c9-071c0a76c3d2.png)

**Comment by kushinauwu** [comment]
I added borders around the pictures so it wouldn't look like they have excess whitespace, and used alternate colours :)

**Comment by nlharris** [comment]
Which page are you talking about above? Not https://www-dev1.open-bio.org/events/bosc/about/?

On https://www-dev1.open-bio.org/events/bosc/about/, if you have time, I was wondering if you could try putting the text under each point next to the photo (some photos could then be made a bit bigger, if there's a lot of text).

**Comment by kushinauwu** [comment]
Sorry, I'm not sure what you meant! Do you mean making the pictures bigger on the About BOSC page for the points with longer text? That can be done! :D
Earlier I was talking about the icons for the logos on the OBF about page :)

**Comment by yochannah** [comment]
Looks good to me!
