### ISSUE TITLE
Homepage - paragraph content sometimes overlaps the image and is hard to read 

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#3]
This is how the homepage looks on my laptop screen: 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/9271438/50374036-a2e0d400-05df-11e9-8983-d72e50426150.png">

I'd suggest we either figure out a way to make the text not overlap, or give it a pale background that makes it readable when it does intrude onto the image. Either should be fine according to your preferences. 

Below is the `<p>` element with a background of `rgba(255,255,255,0.4)` (white, with 40% opacity) in devtools). 

<img width="590" alt="image" src="https://user-images.githubusercontent.com/9271438/50374026-83e24200-05df-11e9-8b71-54387cd360ba.png">

**Comment by kushinauwu** [comment]
It seems better to just make them not overlap. I used the image as a background image for the div, probably not a wise idea. Might be better to put it in a separate column group.

**Comment by kushinauwu** [comment]
I resized my browser window to the point the text started overlapping like that and fixed the CSS. It looks like this now.
![image](https://user-images.githubusercontent.com/14867092/50479720-eda68580-09fd-11e9-9e09-88cfad0d0ae7.png)
If it looks alright in your console too, it should be okay to close this issue :)

**Comment by yochannah** [comment]
@kushinauwu I've just pulled to my local wordpress and it looks much better! The next breakpoint down on a slightly narrower screen looks a little odd, though: 

<img width="744" alt="image" src="https://user-images.githubusercontent.com/9271438/50528890-f4f68d80-0ae8-11e9-955f-dfd239589962.png">

If you narrow the screen even further, the final breakpoint it looks good again, so it's just the middle one that's odd
