### ISSUE TITLE
board members: break to two columns a little earlier

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#38]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/9271438/52818274-342f6c80-309e-11e9-90d5-7b37d2d3cb84.png">
text gets a little narrow and overlappy before it goes to two columns. We might want a minimum width for the paragraphs and/or maybe just break to the two-column layout a little earlier?

**Comment by kushinauwu** [comment]
Used the word-break property fir this and it seems alright now. But I kept it to 3 columns because it started to seem better width-wise... I'm not sure if it is good though!

**Comment by yochannah** [comment]
it's definitely a little better, but we're still getting some overlap: 
<img width="481" alt="image" src="https://user-images.githubusercontent.com/9271438/52904430-21df3b00-3224-11e9-9aad-d96eefa5c067.png">

(as a side note, I think the images are stretching rather than retaining their aspect ratio, too)

**Comment by kushinauwu** [comment]
I made some changes, it looks fine now but might need review! :)

**Comment by yochannah** [comment]
It now looks great in three cols! Still gets a tiny bit the same on two cols when we get smaller: 
![image](https://user-images.githubusercontent.com/9271438/53254532-70288a00-36bb-11e9-8385-0034c68a00e2.png) (this was the Galaxy S9 emulator screen in my FF devtools)

**Comment by kushinauwu** [comment]
I did use break-word for links too, so it really shouldn't be doing that :( I tried going real low on the screen-width and it just broke off the part after B to the next line. Perhaps making the font size smaller might help?  I'll try bumping it down by a little

**Comment by nlharris** [comment]
The layout on the Board page looks good now! The one thing I noticed was that some board member photos are wider than others, which looks a little odd--particularly Peter C's, whose photo is inexplicably wide (I realize it has extra whitespace, but it *looks* inexplicable!). It seems like the photos could all be cropped to the narrower width of Heather's without losing anything.

**Comment by kushinauwu** [comment]
I cropped the pictures to squares and now they're all equally sized :D
@yochannah is the text overlap still persisting?

**Comment by yochannah** [comment]
it still is, unfortunately -
[image: image.png]

maybe we want to break to 1 column at around 420px wide? Any narrower than
that and this happens (at mobile phone widths, generally)

**Comment by yochannah** [comment]
whoops, it didn't add the image.
425 px: ok
<img width="449" alt="image" src="https://user-images.githubusercontent.com/9271438/53523891-f555d980-3ad5-11e9-82f6-e22a2e13787a.png">

any narrower: overlap:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/9271438/53523926-043c8c00-3ad6-11e9-86f7-4d5bba50902d.png">

**Comment by kushinauwu** [comment]
Ahhh, I see. It's okay, we have a breakpoint now so I'll set it to be 1 column after 425px!

**Comment by nlharris** [comment]
I tried making my browser (Chrome) narrower and the text below the board members didn't overlap, but a weird thing happened: when the window got to a certain point of narrowness, the text suddenly became huge!
<img width="998" alt="screen shot 2019-02-27 at 2 15 46 pm" src="https://user-images.githubusercontent.com/348704/53526914-5495f880-3a9a-11e9-9b36-4a156aa1865c.png">
<img width="687" alt="screen shot 2019-02-27 at 2 16 00 pm" src="https://user-images.githubusercontent.com/348704/53526915-56f85280-3a9a-11e9-8400-4ea1c503ca54.png">

**Comment by kushinauwu** [comment]
Hmm I can't tell why the font got so big! That's definitely weird. I did change it to be one column after 425px. Maybe these issues could be related?

**Comment by yochannah** [comment]
around about 760px the change happens for me

**Comment by kushinauwu** [comment]
This seems fixed too!  :)
