### ISSUE TITLE
Navbar shouldn't jump when hovering over content

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#39]
I screenshotted it:

![out](https://user-images.githubusercontent.com/9271438/52821678-7315f000-30a7-11e9-9c0a-0ab14f846492.gif)

**Comment by kushinauwu** [comment]
I updated the site and it isn't doing that anymore! I had set a transparent border for some reason and that was causing the jumpy thing. Why did I even do that! 
Also, I did have to clear my cache before i could see the changes though. The site is probably caching too much, is it something we should look to fix?

**Comment by yochannah** [comment]
This issue is fixed! 

I'm not too worried about the caching - once we have the site live, styles will be stable so caching will be good. btw, in chrome and FF you can disable caching whenever your dev tools are open - this is from the settings menu on my firefox developer edition dev tools:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/9271438/52904616-5c49d780-3226-11e9-9aae-e99e6ce2d770.png">
