### ISSUE TITLE
top left corner logo - use transparent background

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#4]
<img width="336" alt="image" src="https://user-images.githubusercontent.com/9271438/50374304-079e2d80-05e4-11e9-9165-2f5f408f65c4.png">
We could use a transparent background image for the header rather than a white background, to prevent the notable edges of the logo as shown in the screenshot above.

**Comment by kushinauwu** [comment]
Fixed it! I'll close this issue now :)
