### ISSUE TITLE
breadcrumbs sometimes hidden by navbar

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#41]
@yochannah to add screencast

**Comment by yochannah** [comment]
![breadcrumbs](https://user-images.githubusercontent.com/9271438/52913216-db392180-32b3-11e9-87d4-3b5c25e5a029.gif)

**Comment by kushinauwu** [comment]
I think this might be fixed, it looks alright on my machine now, so I'll put a label on this ! :)

**Comment by yochannah** [comment]
This is fixed! :100:
