### ISSUE TITLE
Travel awards sub menu going out of bounds

### ISSUE THREAD

**Issue by kushinauwu** [kushinauwu/OBF-Homepage-New#43]
![image](https://user-images.githubusercontent.com/14867092/53009559-d31ee480-3461-11e9-9934-36dfafea37c0.png)

It looks like the menu is overflowing on my browser, needs checking if this is the case for everyone or if it's like this just on my browser.

**Comment by kushinauwu** [comment]
This seems pretty much solved on my console. Might need checking though!

**Comment by yochannah** [comment]
Travel awards looks great, but now I get it for projects 😆 it's like dominoes

<img width="923" alt="image" src="https://user-images.githubusercontent.com/9271438/53200184-d27c7e80-3618-11e9-815d-dc212cc45ba7.png">

what logic are you using to fix it?

**Comment by kushinauwu** [comment]
Ahh, I was trying to fix it by decreasing the left and right padding. And the default white-spacing was nowrap so it wouldn't help with any amount of padding. Now I just changed it to normal for lower window sizes and kept the width of the second level menu items list to 120% instead of auto. It looks alright now (I think), something like this 
![image](https://user-images.githubusercontent.com/14867092/53229531-73ffe080-36aa-11e9-9739-22ce4ca0a138.png)

**Comment by yochannah** [comment]
I wonder if it might be worth checking if the menu width +its left margin is equal to greater the width of the screen, to make sure it works for projects too? (if that makes sense?)

**Comment by kushinauwu** [comment]
Looks somewhat like this for the Projects section!
![capture](https://user-images.githubusercontent.com/14867092/53584353-6a461380-3ba9-11e9-8f13-928e6d9a0ad7.JPG)

**Comment by yochannah** [comment]
I think we can close this!
