### ISSUE TITLE
Style rendering problems under Chrome v72.0

### ISSUE THREAD

**Issue by peterjc** [kushinauwu/OBF-Homepage-New#44]
Testing on macOS with Safari v12.0.3, test site https://www-dev1.open-bio.org/ looks fine:

<img width="1193" alt="screenshot 2019-02-19 11 09 41" src="https://user-images.githubusercontent.com/63959/53010941-16179280-3437-11e9-9dfa-7e186fc8e6f9.png">

However, with Chrome v72.0, there are vertical space problems with the top banner:

<img width="1161" alt="screenshot 2019-02-19 11 09 54" src="https://user-images.githubusercontent.com/63959/53010948-1adc4680-3437-11e9-8229-a9e3a1c6a4a2.png">

Also the breadcrumbs on the news/blog posts:

<img width="1161" alt="screenshot 2019-02-19 11 12 34" src="https://user-images.githubusercontent.com/63959/53011034-4ceda880-3437-11e9-895d-baa5152b9e9c.png">

**Comment by kushinauwu** [comment]
That definitely looks weird. The breadcrumbs aren't supposed to have bullet styles. I'll check the code on the live site!

**Comment by kushinauwu** [comment]
just updated the site, and this looks fixed on my local machine. I'll mark this for review :)

**Comment by peterjc** [comment]
Looks good here too, thank you.
