### ISSUE TITLE
footer subscribe box

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#45]
![image](https://user-images.githubusercontent.com/9271438/53255481-9a7b4700-36bd-11e9-9a9d-40331cc0d20a.png)
 this box doesn't seem to do anything - I'd suggest we perhaps just remove it and replace with a link to the mailing lists here: https://mailman.open-bio.org/mailman/listinfo (unless @pjacock has any other suggestions? Peter, I'm pinging you specifically since you authored https://news.open-bio.org/2017/12/15/mailing-list-consolidation/ but maybe I should be asking someone else? )

**Comment by yochannah** [comment]
instead remove this section entirely and add to the connect section with the github and tiwtter icons

**Comment by kushinauwu** [comment]
Merged the connect and the mailing list section. :)
