### ISSUE TITLE
volunteer for BOSC! goes nowhere

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#47]
On the homepage, the bosc volunteering link doesn't go anywhere. Is this because we need something to link it *to*?
![image](https://user-images.githubusercontent.com/9271438/53255919-900d7d00-36be-11e9-9afe-57ae7cd2c4f5.png)

**Comment by kushinauwu** [comment]
I had forgotten to link it here ! IT should redirect to the 'get involved' part of the BOSC pages! Just fixed it!

**Comment by kushinauwu** [comment]
This links properly now!
