### ISSUE TITLE
justify text on bosc page 

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#49]
via @nlharris : on the bosc About page, the “channels” section has some justified text that needs to be unjustified:

![image](https://user-images.githubusercontent.com/9271438/53299273-cd454c80-382f-11e9-8179-c8da38e7c38a.png)

**Comment by nlharris** [comment]
ha, I think the title of this issue should be "UNjustify text on bosc pages". 😀
Other places also have justified text that should be unjustified, e.g. "Contact" in footer in https://www-dev1.open-bio.org/about/ and other pages

**Comment by kushinauwu** [comment]
I removed that section and merged it into the footer as you suggested for a different issue. Good catch for the about page!
 (Just adding this here for my reference) 
- [x] Check footer alignments

- [ ] 

- [ ]

**Comment by kushinauwu** [comment]
The footers on the other pages are fixed! I'll close this issue since we gremoved the channels part and moved it to the footer :)
