### ISSUE TITLE
Lgiht text on light buttons a little hard to read. 

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#5]
Example: 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/9271438/50374383-0de0d980-05e5-11e9-8449-5e07a386fa88.png">

Dark text, or a slight dark text shadow on the light text, might make it more readable.

**Comment by kushinauwu** [comment]
Maybe something like this? 
![image](https://user-images.githubusercontent.com/14867092/50480213-87f0d400-09d2-11e9-900a-db52122cc3e4.png)

**Comment by yochannah** [comment]
I've pulled locally and it looks good!
