### ISSUE TITLE
BOSC event links goes to page that is not BOSC page

### ISSUE THREAD

**Issue by nlharris** [kushinauwu/OBF-Homepage-New#51]
On the home page, the Upcoming Events pane shows BOSC. This is in fact the most prominent, visible mention of BOSC on the page. However, when you click the pear, you get to an uninformative event page: https://www-dev1.open-bio.org/?obf-events=temp-event-2
Would it be possible to make that BOSC pear link to the main BOSC page? And, as a more general request, is there a way to allow us to configure the Events links to go where we want, and not necessarily to an event landing page?

**Comment by kushinauwu** [comment]
Good call! I added a field to the events editor, where you can specify where you want the post linked. If nothing is specified there, then it'll lead to just the event page with the summary.
![image](https://user-images.githubusercontent.com/14867092/53523049-c81f2080-3b01-11e9-89dd-4e1a9aa749ff.png)

The link opens in a new tab. Would this be alright? We can have it opening in the same tab too.

**Comment by nlharris** [comment]
yes, that sounds good! thanks!

**Comment by nlharris** [comment]
I just noticed that the BOSC and CoFest icons under UPCOMING EVENTS go to placeholder pages, not the actual event pages. I will try to fix this tomorrow.

**Comment by nlharris** [comment]
I wanted to assign this to myself but don't seem to have the right privileges to do that--can you grant me that privilege, Yo? (And how come I can't @ you?)
