### ISSUE TITLE
Make "Schedule" on BOSC menu hierarchical

### ISSUE THREAD

**Issue by nlharris** [kushinauwu/OBF-Homepage-New#52]
I am open to comments on this from other BOSC organizers, but I was thinking we should make a few of the top-level menu items subitems under Schedule. Sometimes we might not have all of them (e.g., we might not have a panel this year).

Now:
About	  Submit      Schedule 	      Keynotes	       Panel 	 BoFs	    CollaborationFest	   Sponsors

Suggested:
About BOSC	  Submit      Schedule 	    CollaborationFest	   Sponsors

Where Schedule is a submenu containing:
	Complete schedule  [links to current Schedule page]
	Keynotes and Panel
	BoFs

**Comment by kushinauwu** [comment]
Made the sub menu :) Even in case there's no panel, that page can be easily removed and added to the menu items via the WP dashboard, so I think it shouldn't be much of a problem even if the submenu is to be used or no used.

**Comment by nlharris** [comment]
thanks, looks good!
