### ISSUE TITLE
Change wording at top of home page

### ISSUE THREAD

**Issue by nlharris** [kushinauwu/OBF-Homepage-New#53]
It could be that this is a change I could easily make myself--if so, you can leave this issue open and assign to me.

ABOUT THE OBF
The Open Bioinformatics Foundation is a non-profit, volunteer-run group for Open Source software development and Open Science within the biological research community.
->
The Open Bioinformatics Foundation is a non-profit, volunteer-run group that promotes open source software development and Open Science within the biological research community.
It runs the annual Bioinformatics Open Source Conference (BOSC).  [link the last 5 words to the BOSC page]

**Comment by kushinauwu** [comment]
Ah you can change it easily. But since it was just a little edit, i went ahead and edited the text :)
