### ISSUE TITLE
"Join" wording and links

### ISSUE THREAD

**Issue by nlharris** [kushinauwu/OBF-Homepage-New#54]
It occurred to me that it might not be easy for me to change footers by myself, so I would like to request these changes.
OBF footer:
Instead of "Join our mailing list for occasional announcements or to ask questions" make it "Join the OBF mailing list" and link to https://mailman.open-bio.org/mailman/listinfo/open-bio-announce

BOSC footer: can it be different from the OBF footer? That would be nice. (If not, let me know and I'll come up with a Plan B.)
Remove ORGANIZATION / By-Laws / Code of Conduct / Calendar
Change "Join our mailing list for occasional announcements or to ask questions"
to
Follow BOSC on Twitter: @OBF_BOSC, #bosc2019
Join the BOSC announcements mailing list [link to https://mailman.open-bio.org/mailman/listinfo/bosc-announce]
Questions? Want to volunteer? Contact the organizers at obf-bosc@googlegroups.com

**Comment by nlharris** [comment]
Oh yeah--and the "Contact" box on the BOSC page can go if that info is added to the footer of the BOSC pages.

**Comment by kushinauwu** [comment]
Yep! It's totally possible. I just created a footer for the BOSC pages. I'll add in the content now. Thanks for the ready content! :D

**Comment by kushinauwu** [comment]
Fixed this one! Does it seem better now?
![image](https://user-images.githubusercontent.com/14867092/53449123-2636ff80-3a3f-11e9-9715-90133910d893.png)

**Comment by kushinauwu** [comment]
Hmm I just realized the icons don't look the same size.

- [x] Make icons the same size

**Comment by yochannah** [comment]
Looking pretty good

- [x] I think the icons would look okay at current sizes so long as they were all horizontally centered.

- [x] we might want to make sure the left side of the paragraph text aligns with the left side of CONNECT though.

**Comment by nlharris** [comment]
Thanks! Don't need G+, that's basically a dead social medium.
What about replacing G+ with a mailbox icon and putting "bosc-announce" under it (and taking out of the text on the left)?

BTW, with this info now in the footer, the CONTACT box on https://www-dev1.open-bio.org/events/bosc/ is redundant info. Can you replace it with the "Summaries of BOSC 2017" info? (Or will that take up too much vertical space?)

**Comment by kushinauwu** [comment]
Mailbox icon sounds like a good idea! 
Summaries of BOSC 2017 isn't taking up much space. Looks like this. I didn't edit the title, so it still reads as 'contact'! Oops!

![image](https://user-images.githubusercontent.com/14867092/53450987-ae1f0880-3a43-11e9-92d8-1eb4295feea0.png)

**Comment by kushinauwu** [comment]
I moved the summaries down next to the Previous BOSCs tab, and added better icons for the footer too!

**Comment by nlharris** [comment]
Thanks, looking nice! I think we can change "Join the OBF mailing list" in the OBF page footer to the mail icon. I would prefer a simpler mail icon that's just an envelope--the @ in the icon in the BOSC footer seems Twitter-like to me

**Comment by yochannah** [comment]
might it be possible a user would think that the plain old mail icon meant "Email the OBF (board of directors)" rather than the mailing list?

**Comment by nlharris** [comment]
maybe! do you think the @ makes it look more mailing-list-like? or is there another icon that's standard for mailing lists?

**Comment by yochannah** [comment]
hmm, I don't think there is a standard mailing list icon I can think of. I'm also not strongly opposed to just having the mail icon :)

**Comment by kushinauwu** [comment]
A search turned up a literal mail icon with a list inside! XD [https://thenounproject.com/search/?q=mailing%20list&i=1144663](url)
Though I guess it seems more like a newsletter?

**Comment by nlharris** [comment]
I think that icon would be fine

**Comment by kushinauwu** [comment]
I changed the icon! Changed the text in the OBF footer to a mailing list icon similar to this one too :)

**Comment by nlharris** [comment]
👍
