### ISSUE TITLE
breadcrumb left alignment

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#55]
![image](https://user-images.githubusercontent.com/9271438/53449304-6ed7c400-3a11-11e9-8b43-738875b5b429.png)

can we make the breadcrumbs align with the content where possible? red line included to show misalignment.

**Comment by kushinauwu** [comment]
OH, I see it. I'd set a margin on the left to make space between the breadcrumbs. Might be a better choice to set the right margins instead!

**Comment by kushinauwu** [comment]
I had indeed set a left padding for this! Removed that and it aligns well now :D I'll close this issue!
