### ISSUE TITLE
broken links in fellowship menu

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#57]
the top few links in this menu are broken:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/9271438/53522910-50d29800-3ad3-11e9-9e1d-db58bb9ccedf.png">
"see all details" works though

**Comment by kushinauwu** [comment]
OH! Thanks, I'd forgotten this!

**Comment by kushinauwu** [comment]
Fixed this!
