### ISSUE TITLE
Centered alignment of headers on About page looks odd

### ISSUE THREAD

**Issue by nlharris** [kushinauwu/OBF-Homepage-New#58]
The headers under Get Involved on https://www-dev1.open-bio.org/events/bosc/about/ are centered-aligned to the page, but that makes their alignment with respect to the text that follows them look kind of random. Can you left-align those headers with the paragraph(s) of text that follow them?
<img width="855" alt="screen shot 2019-02-27 at 3 48 21 pm" src="https://user-images.githubusercontent.com/348704/53531229-83ff3200-3aa7-11e9-94ae-e45eff2d8b25.png">

**Comment by kushinauwu** [comment]
I fixed this one! I'll mark it for review :D

**Comment by nlharris** [comment]
looks better now, thanks!
