### ISSUE TITLE
Absolute URLs may break

### ISSUE THREAD

**Issue by nlharris** [kushinauwu/OBF-Homepage-New#59]
I've noticed that a lot of the pages have images and links that are absolute URLs that include https://www-dev1.open-bio.org/. I'm worried that these will all break when we change the URL of the site. Is there an easy way to change them all at that point?

**Comment by kushinauwu** [comment]
No, they wont. The URLS are changed accordingly by the importer plugin used [https://wordpress.org/plugins/all-in-one-wp-migration/](url)
