### ISSUE TITLE
Some items floating off the left of the screen

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#7]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/9271438/50374497-1c2ff500-05e7-11e9-866e-b8b676067826.png">

In bootstrap this usually is a result of too many rows inside rows. Aim for 1 container with 1 row inside, if possible.

**Comment by kushinauwu** [comment]
Your suggestion worked great! I'll keep this issue here till it all seems to be working well on your end as well!

**Comment by yochannah** [comment]
This looks fixed to me!! Nice one!
