### ISSUE TITLE
text shouldn't have same-color text shadow - makes it seem blurry

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#8]
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/9271438/50374590-3b7b5200-05e8-11e9-9cdb-92932817cec7.png">
example screenshot above - either no text shadow or a light text shadow would probably work better here. I do like the pear-shaped image cutouts!

**Comment by kushinauwu** [comment]
![image](https://user-images.githubusercontent.com/14867092/50480532-76272500-0a02-11e9-9e2a-bac9021b5bae.png)
Made the text shadow lighter, Does this look better?

**Comment by yochannah** [comment]
I'll be honest, it still looks pretty blurry to me :) maybe no shadow?

**Comment by yochannah** [comment]
Whoops - I think that might be the image quality, not the code. Let me check properly on my wordpress.

**Comment by yochannah** [comment]
this is better! Nice one. 👍
