### ISSUE TITLE
Navbar - styling suggestions

### ISSUE THREAD

**Issue by yochannah** [kushinauwu/OBF-Homepage-New#9]
<img width="267" alt="image" src="https://user-images.githubusercontent.com/9271438/50374611-97de7180-05e8-11e9-804f-a7e178e46323.png">

A few thoughts on the styling of the navbar.

- [x] Note the grey line through fellowships - I think this is the `.nav .open > a, .nav .open > a:focus, .nav .open > a:hover` styling clashing oddly with the styling for the parent element's `#menu-main-menu .menu-item:hover` styles. 
- [x] the blue bar for coverage should extend all the way to the right and have better contrast with the text. 
- [x] this one is less important, but the highly rounded corners make the menu seem a little unrelated to the button title. I wonder if we could shape it more like a single unit, a bit like this: 

<img width="335" alt="image" src="https://user-images.githubusercontent.com/9271438/50374677-ec362100-05e9-11e9-87ac-d9e0e8ab4767.png">

**Comment by kushinauwu** [comment]
![image](https://user-images.githubusercontent.com/14867092/50480639-28f78300-0a03-11e9-8faf-bbae4d25aa15.png)
Is this better?

**Comment by kushinauwu** [comment]
![image](https://user-images.githubusercontent.com/14867092/50480736-b2905c00-09d5-11e9-961e-200d125b1507.png)
 is this better than before?

**Comment by yochannah** [comment]
Much!
